--
-- SOUTHWIND  (User) 
--
CREATE USER SOUTHWIND 
IDENTIFIED BY SOUTHWIND 
DEFAULT TABLESPACE USERS 
TEMPORARY TABLESPACE TEMP 
PROFILE DEFAULT 
ACCOUNT UNLOCK ;
  -- 2 Roles for SOUTHWIND 
  GRANT RESOURCE TO SOUTHWIND;
  GRANT CONNECT TO SOUTHWIND;
  ALTER USER SOUTHWIND DEFAULT ROLE ALL;
  -- 6 System Privileges for SOUTHWIND 
  GRANT CREATE PROCEDURE TO SOUTHWIND;
  GRANT CREATE TABLE TO SOUTHWIND;
  GRANT CREATE TRIGGER TO SOUTHWIND;
  GRANT CREATE SEQUENCE TO SOUTHWIND;
  GRANT CREATE VIEW TO SOUTHWIND;
  GRANT UNLIMITED TABLESPACE TO SOUTHWIND;