using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("ObjectMapper .NET")]
[assembly: AssemblyDescriptionAttribute("The .NET Persistence Framework for Oracle, Microsoft SQL Server, Microsoft Access" +
    " and XML Files.")]
[assembly: AssemblyCompanyAttribute("Gerhard Stephan Softwareentwicklung")]
[assembly: AssemblyProductAttribute("ObjectMapper .NET")]
[assembly: AssemblyCopyrightAttribute("(c) by Gerhard Stephan")]
[assembly: AssemblyVersionAttribute("3.0.0.0")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyKeyFileAttribute("..\\..\\ObjectMapper.snk")]
[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]

