using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyTitleAttribute("ObjectMapper .NET")]
[assembly: AssemblyDescriptionAttribute("The .NET Persistence Framework for Oracle, Microsoft SQL Server, Microsoft Access" +
    " and XML Files.")]
[assembly: AssemblyCompanyAttribute("Gerhard Stephan Softwareentwicklung")]
[assembly: AssemblyProductAttribute("ObjectMapper .NET")]
[assembly: AssemblyCopyrightAttribute("(c) by Gerhard Stephan")]
[assembly: AssemblyVersionAttribute("4.5.0.6")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AssemblyKeyFileAttribute("..\\..\\ObjectMapper.snk")]
[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]

